name: Release (latest)

on: workflow_dispatch

jobs:
  release:
    strategy:
      matrix:
        package:
          - drizzle-orm
          # - drizzle-orm-mysql
          - drizzle-orm-pg
          - drizzle-orm-sqlite
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        run: |
          latest=$(npm view --json ${{ matrix.package }} dist-tags.latest | jq -r)
          version=$(jq -r .version package.json)

          if [[ $latest != $version ]]; then
            echo "Latest:  $latest"
            echo "Current: $version"

            (cd .. && pnpm i)
            pnpm run release

            # Post release message to Discord
            curl -X POST -H "Content-Type: application/json" -d "{\"embeds\": [{\"title\": \"New \`${{ matrix.package }}\` release\! 🎉\", \"url\": \"https://www.npmjs.com/package/${{ matrix.package }}\", \"color\": \"12907856\", \"fields\": [{\"name\": \"Version\", \"value\": \"$version\"}]}]}" ${{ secrets.DISCORD_RELEASE_WEBHOOK_URL }}
          else
            echo "Already up to date: $version"
          fi
        working-directory: ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
