name: Release (latest)

on: workflow_dispatch

jobs:
  release:
    strategy:
      matrix:
        package:
          - drizzle-orm
          - drizzle-zod
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Publish
        run: |
          latest="$(npm view --json ${{ matrix.package }} dist-tags.latest | jq -r)"
          version="$(jq -r .version package.json)"

          if [[ "$latest" != "$version" ]]; then
            echo "Latest:  $latest"
            echo "Current: $version"

            is_version_published="$(npm view ${{ matrix.package }} versions --json | jq -r '.[] | select(. == "'$version'") | . == "'$version'"')"
            if [[ "$is_version_published" == "true" ]]; then
              echo "Version $version already published, adding tag $tag"
              npm dist-tag add ${{ matrix.package }}@$version latest
            else
              echo echo "Publishing ${{ matrix.package }}@$version"
              (cd .. && npm run pack -- --filter ${{ matrix.package }})
              npm run publish
            fi

            # Post release message to Discord
            curl -X POST -H "Content-Type: application/json" -d "{\"embeds\": [{\"title\": \"New \`${{ matrix.package }}\` release! 🎉\", \"url\": \"https://www.npmjs.com/package/${{ matrix.package }}\", \"color\": \"12907856\", \"fields\": [{\"name\": \"Tag\", \"value\": \"\`$tag\`\"}]}]}" ${{ secrets.DISCORD_RELEASE_WEBHOOK_URL }}

            # Put version to outputs
            echo "::set-output name=version::$version"
            echo "::set-output name=has_new_release::true"
          else
            echo "Already up to date: $version"
          fi
        working-directory: ${{ matrix.package }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Create GitHub release
        uses: actions/github-script@v6
        if: ${{ steps.release.outputs.has_new_release == 'true' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const fs = require("fs");
              const path = require("path");

              const changelog = fs.readFileSync(path.join(__dirname, "changelogs", "${{ matrix.package }}", "${{ steps.release.outputs.version }}.md"), "utf8");
              const version = "${{ steps.release.outputs.version }}";
              const tag = "latest";
              const release = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag,
                name: `${{ matrix.package }} v${version}`,
                body: changelog,
                draft: true,
              });
              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.data.id,
                name: `${{ matrix.package }}-${version}.tgz`,
                data: fs.readFileSync(path.join(__dirname, "${{ matrix.package }}", "package.tgz")),
              });
            } catch (e) {
              core.setFailed(error.message);
            }
